### ISSUE TITLE
Suggestion: Granaries & Warehouse on "Emptying" Orders

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#69]
Please exclude this thread.

**Comment by cdsmith-umn** [comment]
This would be nice because it takes forever to empty these buildings when you want to do so.

**Comment by crudelios** [comment]
Isn't this now fixed with the option of sending more goods at once?

**Comment by arkimedes1967** [comment]
> Isn't this now fixed with the option of sending more goods at once?

No, i'm playing with the Augustus 2.0.1.58 version and the issue persist. The cartpusher starts emptying the granary 1 load at the time, as the video shows.

https://user-images.githubusercontent.com/64329357/105618726-8fb61900-5de2-11eb-8f00-b8318d578da2.mp4

**Comment by crudelios** [comment]
Ok, thanks. I'll see if it makes sense to empty 4 goods at a time with the option enabled.

**Comment by arkimedes1967** [comment]
> Ok, thanks. I'll see if it makes sense to empty 4 goods at a time with the option enabled.

While you are seeing it, please consider the follow. When emptying a **granary** and/or a **warehouse**:

- Start emptying **only** the resources that are 'Not accepting';
- If resources remain 'Accepting' or 'Getting goods' status, **do not** start emptying them;
- If player wants start emptying **all resources**, he must first click on the 'X' (refuse goods) and then 'Start emptying' button.

With this options player may selectively empty a/some resource(s) or all of then if he really wants to.

**Comment by crudelios** [comment]
I have no time for such an overhaul right now. One thing at a time,or nothing will get done!

**Comment by arkimedes1967** [comment]
If you think is best, i may propose it on the Discussions tab.

**Comment by crudelios** [comment]
I'd rather have a per-resource "Empty" option, like in Pharaoh actually. Much more flexible!

**Comment by arkimedes1967** [comment]
> I'd rather have a per-resource "Empty" option, like in Pharaoh actually. Much more flexible!

Ideally, yes, but i thought it was more difficult to implement, since you've to create a new 'Send goods elsewhere' order.
